<?php

return [
    'overrides' => [
        '' => [
            'meta_title' => 'Cash For Junk Cars: Sell Yours First - Free Towing',
            'focus_keyword' => 'Cash For Junk Cars',
            'meta_description' => 'Cashing Carz Orlando offers top dollar for your vehicle. Fast pickup, instant quotes, and Cash For Junk Cars services in Orlando area.',
            'og_title' => 'Cash For Junk Cars: Sell Yours First - Free Towing',
            'og_description' => 'Cashing Carz Orlando offers top dollar for your vehicle. Fast pickup, instant quotes, and Cash For Junk Cars services in Orlando area.',
        ],
        'services' => [
            'meta_title' => 'Save Space and Money with Our Junk Car Removal Services',
            'focus_keyword' => 'Junk Car Removal Services',
            'meta_description' => 'Cashing Carz Orlando offers fast, reliable Junk Car Removal Services in Orlando. Get instant cash for unwanted vehicles today!',
            'og_title' => 'Save Space and Money with Our Junk Car Removal Services',
            'og_description' => 'Cashing Carz Orlando offers fast, reliable Junk Car Removal Services in Orlando. Get instant cash for unwanted vehicles today!',
        ],
        'sells' => [
            'meta_title' => 'Sell Junk Car for Cash - Get a Quick Online Quote',
            'focus_keyword' => 'Sell Junk Car for Cash',
            'meta_description' => 'Sell Junk Car for Cash in Orlando fast. Get top dollar, free towing, and instant quotes. Turn your old car into cash today with ease.',
            'og_title' => 'Sell Junk Car for Cash - Get a Quick Online Quote',
            'og_description' => 'Sell Junk Car for Cash in Orlando fast. Get top dollar, free towing, and instant quotes. Turn your old car into cash today with ease.',
        ],
        'donate' => [
            'meta_title' => 'Donate Your Junk Car | Cashingcarz Orlando',
            'focus_keyword' => 'Donate Your Junk Car',
            'meta_description' => 'Donate Your Junk Car in Orlando with Cashing Carz. Free towing, fast pickup, and support a good cause with your unwanted vehicle.',
            'og_title' => 'Donate Your Junk Car | Cashingcarz Orlando',
            'og_description' => 'Donate Your Junk Car in Orlando with Cashing Carz. Free towing, fast pickup, and support a good cause with your unwanted vehicle.',
        ],
        'get_offer' => [
            'meta_title' => 'Get Offer | Cashingcarz Orlando',
            'focus_keyword' => 'Get Offer',
            'meta_description' => 'Get Offer for your junk car in minutes with Cashing Carz Orlando. Fast quotes, top cash offers, and hassle-free vehicle removal today.',
            'og_title' => 'Get Offer | Cashingcarz Orlando',
            'og_description' => 'Get Offer for your junk car in minutes with Cashing Carz Orlando. Fast quotes, top cash offers, and hassle-free vehicle removal today.',
        ],
        'testimonial' => [
            'meta_title' => 'Testimonial | Cashingcarz Orlando',
            'focus_keyword' => 'Testimonial',
            'meta_description' => 'Read customer testimonials at CashingCarz Orlando to see trusted reviews, fast cash offers, and hassle-free car selling service.',
            'og_title' => 'Testimonial | Cashingcarz Orlando',
            'og_description' => 'Read customer testimonials at CashingCarz Orlando to see trusted reviews, fast cash offers, and hassle-free car selling service.',
        ],
        'referrals' => [
            'meta_title' => 'Earn $100 - Referral Program | Cashingcarz Orlando',
            'focus_keyword' => 'Referral Program',
            'meta_description' => 'Join the Referral Program at CashingCarz Orlando and earn rewards for every successful referral. Start sharing and get paid today!',
            'og_title' => 'Earn $100 - Referral Program | Cashingcarz Orlando',
            'og_description' => 'Join the Referral Program at CashingCarz Orlando and earn rewards for every successful referral. Start sharing and get paid today!',
        ],
        'contact' => [
            'meta_title' => 'Contact Us | Cashingcarz Orlando',
            'focus_keyword' => 'Contact Us',
            'meta_description' => 'Contact Us at Cashing Carz Orlando for fast, hassle-free junk car removal. Get a free quote and turn your old car into cash today!',
            'og_title' => 'Contact Us | Cashingcarz Orlando',
            'og_description' => 'Contact Us at Cashing Carz Orlando for fast, hassle-free junk car removal. Get a free quote and turn your old car into cash today!',
        ],
        'blog' => [
            'meta_title' => 'Insurance Blog & Tips | Dhuka Insurance',
            'focus_keyword' => 'Article About Cash for Cars',
            'meta_description' => 'Explore our blog for every Article About Cash for Cars—tips, pricing insights, and easy ways to sell your car fast in Orlando.',
            'og_title' => 'Insurance Blog & Tips | Dhuka Insurance',
            'og_description' => 'Explore our blog for every Article About Cash for Cars—tips, pricing insights, and easy ways to sell your car fast in Orlando.',
        ],
    ],

    'location_overrides' => [
        'orlando-fl' => [
            'meta_title' => 'Junk Car Removal Orlando, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Orlando',
            'meta_description' => 'Junk Car Removal Orlando - fast, free pickup and top cash offers. Sell your junk car in Orlando, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Orlando, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Orlando - fast, free pickup and top cash offers. Sell your junk car in Orlando, FL today with hassle-free service.',
        ],
        'winter-park-fl' => [
            'meta_title' => 'Junk Car Removal Winter Park, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Winter Park FL',
            'meta_description' => 'Junk Car Removal Winter Park - fast, free pickup and top cash offers. Sell your junk car in Winter Park, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Winter Park, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Winter Park - fast, free pickup and top cash offers. Sell your junk car in Winter Park, FL today with hassle-free service.',
        ],
        'maitland-fl' => [
            'meta_title' => 'Junk Car Removal Maitland, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Maitland FL',
            'meta_description' => 'Junk Car Removal Maitland - fast, free pickup and top cash offers. Sell your junk car in Maitland, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Maitland, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Maitland - fast, free pickup and top cash offers. Sell your junk car in Maitland, FL today with hassle-free service.',
        ],
        'altamonte-springs-fl' => [
            'meta_title' => 'Junk Car Removal Altamonte Springs, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Altamonte Springs FL',
            'meta_description' => 'Junk Car Removal Altamonte Springs - fast, free pickup and top cash offers. Sell your junk car in Altamonte Springs, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Altamonte Springs, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Altamonte Springs - fast, free pickup and top cash offers. Sell your junk car in Altamonte Springs, FL today with hassle-free service.',
        ],
        'casselberry-fl' => [
            'meta_title' => 'Junk Car Removal Casselberry, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Casselberry FL',
            'meta_description' => 'Junk Car Removal Casselberry - fast, free pickup and top cash offers. Sell your junk car in Casselberry, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Casselberry, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Casselberry - fast, free pickup and top cash offers. Sell your junk car in Casselberry, FL today with hassle-free service.',
        ],
        'winter-garden-fl' => [
            'meta_title' => 'Junk Car Removal Winter Garden, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Winter Garden FL',
            'meta_description' => 'Junk Car Removal Winter Garden - fast, free pickup and top cash offers. Sell your junk car in Winter Garden, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Winter Garden, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Winter Garden - fast, free pickup and top cash offers. Sell your junk car in Winter Garden, FL today with hassle-free service.',
        ],
        'ocoee-fl' => [
            'meta_title' => 'Junk Car Removal Ocoee, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Ocoee FL',
            'meta_description' => 'Junk Car Removal Ocoee - fast, free pickup and top cash offers. Sell your junk car in Ocoee, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Ocoee, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Ocoee - fast, free pickup and top cash offers. Sell your junk car in Ocoee, FL today with hassle-free service.',
        ],
        'edgewood-fl' => [
            'meta_title' => 'Junk Car Removal Edgewood, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Edgewood FL',
            'meta_description' => 'Junk Car Removal Edgewood - fast, free pickup and top cash offers. Sell your junk car in Edgewood, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Edgewood, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Edgewood - fast, free pickup and top cash offers. Sell your junk car in Edgewood, FL today with hassle-free service.',
        ],
        'belle-isle-fl' => [
            'meta_title' => 'Junk Car Removal Belle Isle, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Belle Isle FL',
            'meta_description' => 'Junk Car Removal Belle Isle - fast, free pickup and top cash offers. Sell your junk car in Belle Isle, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Belle Isle, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Belle Isle - fast, free pickup and top cash offers. Sell your junk car in Belle Isle, FL today with hassle-free service.',
        ],
        'kissimmee-fl' => [
            'meta_title' => 'Junk Car Removal Kissimmee, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Kissimmee FL',
            'meta_description' => 'Junk Car Removal Kissimmee - fast, free pickup and top cash offers. Sell your junk car in Kissimmee, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Kissimmee, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Kissimmee - fast, free pickup and top cash offers. Sell your junk car in Kissimmee, FL today with hassle-free service.',
        ],
        'sanford-fl' => [
            'meta_title' => 'Junk Car Removal Sanford, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Sanford FL',
            'meta_description' => 'Junk Car Removal Sanford - fast, free pickup and top cash offers. Sell your junk car in Sanford, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Sanford, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Sanford - fast, free pickup and top cash offers. Sell your junk car in Sanford, FL today with hassle-free service.',
        ],
        'apopka-fl' => [
            'meta_title' => 'Junk Car Removal Apopka, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Apopka FL',
            'meta_description' => 'Junk Car Removal Apopka - fast, free pickup and top cash offers. Sell your junk car in Apopka, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Apopka, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Apopka - fast, free pickup and top cash offers. Sell your junk car in Apopka, FL today with hassle-free service.',
        ],
        'lake-mary-fl' => [
            'meta_title' => 'Junk Car Removal Lake Mary, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Lake Mary FL',
            'meta_description' => 'Junk Car Removal Lake Mary - fast, free pickup and top cash offers. Sell your junk car in Lake Mary, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Lake Mary, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Lake Mary - fast, free pickup and top cash offers. Sell your junk car in Lake Mary, FL today with hassle-free service.',
        ],
        'longwood-fl' => [
            'meta_title' => 'Junk Car Removal Longwood, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Longwood FL',
            'meta_description' => 'Junk Car Removal Longwood - fast, free pickup and top cash offers. Sell your junk car in Longwood, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Longwood, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Longwood - fast, free pickup and top cash offers. Sell your junk car in Longwood, FL today with hassle-free service.',
        ],
        'clermont-fl' => [
            'meta_title' => 'Junk Car Removal Clermont, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Clermont FL',
            'meta_description' => 'Junk Car Removal Clermont - fast, free pickup and top cash offers. Sell your junk car in Clermont, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Clermont, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Clermont - fast, free pickup and top cash offers. Sell your junk car in Clermont, FL today with hassle-free service.',
        ],
        'oviedo-fl' => [
            'meta_title' => 'Junk Car Removal Oviedo, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Oviedo FL',
            'meta_description' => 'Junk Car Removal Oviedo - fast, free pickup and top cash offers. Sell your junk car in Oviedo, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Oviedo, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Oviedo - fast, free pickup and top cash offers. Sell your junk car in Oviedo, FL today with hassle-free service.',
        ],
        'st-cloud-fl' => [
            'meta_title' => 'Junk Car Removal St Cloud, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal St Cloud FL',
            'meta_description' => 'Junk Car Removal St Cloud - fast, free pickup and top cash offers. Sell your junk car in St Cloud, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal St Cloud, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal St Cloud - fast, free pickup and top cash offers. Sell your junk car in St Cloud, FL today with hassle-free service.',
        ],
        'sebring-fl' => [
            'meta_title' => 'Junk Car Removal Sebring, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Sebring FL',
            'meta_description' => 'Junk Car Removal Sebring - fast, free pickup and top cash offers. Sell your junk car in Sebring, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Sebring, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Sebring - fast, free pickup and top cash offers. Sell your junk car in Sebring, FL today with hassle-free service.',
        ],
        'palm-bay-fl' => [
            'meta_title' => 'Junk Car Removal Palm Bay, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Palm Bay FL',
            'meta_description' => 'Junk Car Removal Palm Bay - fast, free pickup and top cash offers. Sell your junk car in Palm Bay, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Palm Bay, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Palm Bay - fast, free pickup and top cash offers. Sell your junk car in Palm Bay, FL today with hassle-free service.',
        ],
        'daytona-beach-fl' => [
            'meta_title' => 'Junk Car Removal Daytona Beach, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Daytona Beach FL',
            'meta_description' => 'Junk Car Removal Daytona Beach - fast, free pickup and top cash offers. Sell your junk car in Daytona Beach, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Daytona Beach, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Daytona Beach - fast, free pickup and top cash offers. Sell your junk car in Daytona Beach, FL today with hassle-free service.',
        ],
        'lakeland-fl' => [
            'meta_title' => 'Junk Car Removal Lakeland, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Lakeland FL',
            'meta_description' => 'Junk Car Removal Lakeland - fast, free pickup and top cash offers. Sell your junk car in Lakeland, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Lakeland, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Lakeland - fast, free pickup and top cash offers. Sell your junk car in Lakeland, FL today with hassle-free service.',
        ],
        'deltona-fl' => [
            'meta_title' => 'Junk Car Removal Deltona, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Deltona FL',
            'meta_description' => 'Junk Car Removal Deltona - fast, free pickup and top cash offers. Sell your junk car in Deltona, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Deltona, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Deltona - fast, free pickup and top cash offers. Sell your junk car in Deltona, FL today with hassle-free service.',
        ],
        'palm-coast-fl' => [
            'meta_title' => 'Junk Car Removal Palm Coast, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Palm Coast FL',
            'meta_description' => 'Junk Car Removal Palm Coast - fast, free pickup and top cash offers. Sell your junk car in Palm Coast, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Palm Coast, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Palm Coast - fast, free pickup and top cash offers. Sell your junk car in Palm Coast, FL today with hassle-free service.',
        ],
        'melbourne-fl' => [
            'meta_title' => 'Junk Car Removal Melbourne, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Melbourne FL',
            'meta_description' => 'Junk Car Removal Melbourne - fast, free pickup and top cash offers. Sell your junk car in Melbourne, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Melbourne, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Melbourne - fast, free pickup and top cash offers. Sell your junk car in Melbourne, FL today with hassle-free service.',
        ],
        'leesburg-fl' => [
            'meta_title' => 'Junk Car Removal Leesburg, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Leesburg FL',
            'meta_description' => 'Junk Car Removal Leesburg - fast, free pickup and top cash offers. Sell your junk car in Leesburg, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Leesburg, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Leesburg - fast, free pickup and top cash offers. Sell your junk car in Leesburg, FL today with hassle-free service.',
        ],
        'davenport-fl' => [
            'meta_title' => 'Junk Car Removal Davenport, Florida | Cashingcarz Orlando',
            'focus_keyword' => 'Junk Car Removal Davenport FL',
            'meta_description' => 'Junk Car Removal Davenport - fast, free pickup and top cash offers. Sell your junk car in Davenport, FL today with hassle-free service.',
            'og_title' => 'Junk Car Removal Davenport, Florida | Cashingcarz Orlando',
            'og_description' => 'Junk Car Removal Davenport - fast, free pickup and top cash offers. Sell your junk car in Davenport, FL today with hassle-free service.',
        ],
    ],
];
